version: '3.8'

services:
  db:
    image: postgis/postgis
    container_name: fantasilandia_db
    environment:
      - POSTGRES_DB=fantasilandia
      - POSTGRES_USER=fantasilandia_user
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
